### PR TITLE
Fixed issue with the format of images (now it is CV_32F)

### PR DESCRIPTION
**Pull request by nlyubova**

### CODE REVIEW

**Comment by vrabaud** [comment]
but if the condition passes, the output has the type of the input, hence an inconsistence.

**Comment by nlyubova** [comment]
If condition passes than there already was exactly the same conversion,
Thus it gives 32F for both cases now (before this line was just missing)

**Comment by vrabaud** [comment]
I missed that depth is always CV_32F, thx.

**Comment by nlyubova** [comment]
Vincent,
I've just noticed that you have merged the ecto_image_pipeline but you have
not merged the Linemod. But the commit in ecto_image_pipeline does not work
without the commit in the Linemod. Could you please accept the pull request
for the Linemod?

**Pull request merged**
